# Generated by Django 4.0.5 on 2022-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
